services:
  db_test:
    image: postgres:18
    container_name: gorest_db_test
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb_test
    ports:
      - "5433:5432"
    volumes:
      - db_test_data:/var/lib/postgresql/data

  mysql_test:
    image: mysql:8.0
    container_name: gorest_mysql_test
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb_test
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3307:3306"
    volumes:
      - mysql_test_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  db_test_data:
  mysql_test_data: