// Code generated by gorest. DO NOT EDIT.

package api

import (
	"github.com/gofiber/fiber/v2"
	"github.com/nicolasbonnici/gorest/internal"
	"github.com/nicolasbonnici/gorest/internal/api/resources"
	"github.com/nicolasbonnici/gorest/pkg/database"
)

func RegisterGeneratedRoutes(app *fiber.App, db database.Database, tables map[string]internal.TableSchema, jwtSecret string) {
		resources.RegisterTodoRoutes(app, db)
		resources.RegisterUserRoutes(app, db)
}
