// Code generated by gorest. DO NOT EDIT.

package api

import (
	"github.com/gofiber/fiber/v2"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/nicolasbonnici/gorest/internal"
	"github.com/nicolasbonnici/gorest/internal/api/resources"
)

// RegisterGeneratedRoutes registers all generated resource routes
func RegisterGeneratedRoutes(app *fiber.App, db *pgxpool.Pool, tables map[string]internal.TableSchema, jwtSecret string) {
		resources.RegisterTodoRoutes(app, db, jwtSecret)
		resources.RegisterUserRoutes(app, db, jwtSecret)
}
