// Code generated by gorest. DO NOT EDIT.

package resources

import (
	"github.com/gofiber/fiber/v2"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/nicolasbonnici/gorest/internal/crud"
	"github.com/nicolasbonnici/gorest/internal/api/models"
)

// TodoResource defines REST endpoints for Todo model.
// @Summary Todo resource
// @Description CRUD operations for Todo
// @Tags Todo
type TodoResource struct {
	DB   *pgxpool.Pool
	CRUD *crud.CRUD[models.Todo]
}

func RegisterTodoRoutes(router fiber.Router, db *pgxpool.Pool) {
	res := &TodoResource{
		DB:   db,
		CRUD: crud.New[models.Todo](db),
	}
	router.Get("/todo", res.List)
	router.Get("/todo/:id", res.Get)
	router.Post("/todo", res.Create)
	router.Put("/todo/:id", res.Update)
	router.Delete("/todo/:id", res.Delete)
}

// List Todo
// @Summary List Todo
// @Tags Todo
// @Produce json
// @Success 200 {array} models.Todo
// @Router /todo [get]
func (r *TodoResource) List(c *fiber.Ctx) error {
	items, err := r.CRUD.GetAll(c.Context())
	if err != nil {
		return c.Status(500).JSON(fiber.Map{"error": err.Error()})
	}
	if items == nil {
		items = []models.Todo{}
	}
	return c.JSON(items)
}

// Get Todo by ID
// @Summary Get Todo
// @Tags Todo
// @Produce json
// @Param id path int true "ID"
// @Success 200 {object} models.Todo
// @Router /todo/{id} [get]
func (r *TodoResource) Get(c *fiber.Ctx) error {
	id := c.Params("id")
	item, err := r.CRUD.GetByID(c.Context(), id)
	if err != nil {
		return c.Status(404).JSON(fiber.Map{"error": "Not found"})
	}
	return c.JSON(item)
}

// Create Todo
// @Summary Create Todo
// @Tags Todo
// @Accept json
// @Produce json
// @Param input body models.Todo true "New Todo"
// @Success 201 {object} models.Todo
// @Router /todo [post]
func (r *TodoResource) Create(c *fiber.Ctx) error {
	var item models.Todo
	if err := c.BodyParser(&item); err != nil {
		return c.Status(400).JSON(fiber.Map{"error": "Invalid request body", "details": err.Error()})
	}
	if err := r.CRUD.Create(c.Context(), item); err != nil {
		return c.Status(500).JSON(fiber.Map{"error": err.Error()})
	}
	return c.Status(201).JSON(item)
}

// Update Todo
// @Summary Update Todo
// @Tags Todo
// @Accept json
// @Produce json
// @Param id path int true "ID"
// @Param input body models.Todo true "Updated Todo"
// @Success 200 {object} models.Todo
// @Router /todo/{id} [put]
func (r *TodoResource) Update(c *fiber.Ctx) error {
	id := c.Params("id")
	var item models.Todo
	if err := c.BodyParser(&item); err != nil {
		return c.Status(400).JSON(fiber.Map{"error": "Invalid request body"})
	}
	if err := r.CRUD.Update(c.Context(), id, item); err != nil {
		return c.Status(500).JSON(fiber.Map{"error": err.Error()})
	}
	return c.JSON(item)
}

// Delete Todo
// @Summary Delete Todo
// @Tags Todo
// @Param id path int true "ID"
// @Success 204
// @Router /todo/{id} [delete]
func (r *TodoResource) Delete(c *fiber.Ctx) error {
	id := c.Params("id")
	if err := r.CRUD.Delete(c.Context(), id); err != nil {
		return c.Status(500).JSON(fiber.Map{"error": err.Error()})
	}
	return c.SendStatus(204)
}
