// Code generated by gorest. DO NOT EDIT.

package resources

import (
	"github.com/gofiber/fiber/v2"
	"github.com/nicolasbonnici/gorest/internal"
	"github.com/nicolasbonnici/gorest/internal/crud"
	"github.com/nicolasbonnici/gorest/internal/api/models"
	"github.com/nicolasbonnici/gorest/internal/api/dtos"
	"github.com/nicolasbonnici/gorest/pkg/database"
)

type UserResource struct {
	DB   database.Database
	CRUD *crud.CRUD[models.User]
}

func RegisterUserRoutes(router fiber.Router, db database.Database) {
	res := &UserResource{
		DB:   db,
		CRUD: crud.New[models.User](db),
	}
	router.Get("/users", res.List)
	router.Get("/users/:id", res.Get)
	router.Post("/users", res.Create)
	router.Put("/users/:id", res.Update)
	router.Delete("/users/:id", res.Delete)
}

// modelToUserDTO converts a model to a response DTO
func modelToUserDTO(m models.User) dtos.UserDTO {
	return dtos.UserDTO{
		Id: m.Id,
		Firstname: m.Firstname,
		Lastname: m.Lastname,
		Email: m.Email,
		UpdatedAt: m.UpdatedAt,
		CreatedAt: m.CreatedAt,
	}
}

// userCreateDTOToModel converts a CreateDTO to a model
func userCreateDTOToModel(dto dtos.UserCreateDTO) models.User {
	return models.User{
		Firstname: dto.Firstname,
		Lastname: dto.Lastname,
		Email: dto.Email,
		Password: dto.Password,
	}
}

// userUpdateDTOToModel converts an UpdateDTO to a model
func userUpdateDTOToModel(dto dtos.UserUpdateDTO) models.User {
	return models.User{
		Firstname: dto.Firstname,
		Lastname: dto.Lastname,
		Email: dto.Email,
		Password: dto.Password,
	}
}


// List User
// @Summary List User
// @Tags User
// @Produce json,application/ld+json
// @Success 200 {array} dtos.UserDTO
// @Router /users [get]
func (r *UserResource) List(c *fiber.Ctx) error {
	items, err := r.CRUD.GetAll(c.Context())
	if err != nil {
		return c.Status(500).JSON(fiber.Map{"error": err.Error()})
	}

	// Convert models to DTOs
	dtoItems := make([]dtos.UserDTO, len(items))
	for i, item := range items {
		dtoItems[i] = modelToUserDTO(item)
	}

	return internal.SendFormatted(c, 200, dtoItems)
}

// Get User by ID
// @Summary Get User
// @Tags User
// @Produce json,application/ld+json
// @Param id path int true "ID"
// @Success 200 {object} dtos.UserDTO
// @Router /users/{id} [get]
func (r *UserResource) Get(c *fiber.Ctx) error {
	id := c.Params("id")
	item, err := r.CRUD.GetByID(c.Context(), id)
	if err != nil {
		return c.Status(404).JSON(fiber.Map{"error": "Not found"})
	}

	// Convert model to DTO
	dto := modelToUserDTO(*item)
	return internal.SendFormatted(c, 200, dto)
}

// Create User
// @Summary Create User
// @Tags User
// @Accept json
// @Produce json,application/ld+json
// @Param input body dtos.UserCreateDTO true "New User"
// @Success 201 {object} dtos.UserDTO
// @Router /users [post]
func (r *UserResource) Create(c *fiber.Ctx) error {
	var createDTO dtos.UserCreateDTO
	if err := c.BodyParser(&createDTO); err != nil {
		return c.Status(400).JSON(fiber.Map{"error": "Invalid request body", "details": err.Error()})
	}

	// Convert DTO to model
	item := userCreateDTOToModel(createDTO)

	if err := r.CRUD.Create(c.Context(), item); err != nil {
		return c.Status(500).JSON(fiber.Map{"error": err.Error()})
	}

	// Convert model to response DTO
	dto := modelToUserDTO(item)
	return internal.SendFormatted(c, 201, dto)
}

// Update User
// @Summary Update User
// @Tags User
// @Accept json
// @Produce json,application/ld+json
// @Param id path int true "ID"
// @Param input body dtos.UserUpdateDTO true "Updated User"
// @Success 200 {object} dtos.UserDTO
// @Router /users/{id} [put]
func (r *UserResource) Update(c *fiber.Ctx) error {
	id := c.Params("id")
	var updateDTO dtos.UserUpdateDTO
	if err := c.BodyParser(&updateDTO); err != nil {
		return c.Status(400).JSON(fiber.Map{"error": "Invalid request body"})
	}

	// Convert DTO to model
	item := userUpdateDTOToModel(updateDTO)

	if err := r.CRUD.Update(c.Context(), id, item); err != nil {
		return c.Status(500).JSON(fiber.Map{"error": err.Error()})
	}

	// Convert model to response DTO
	dto := modelToUserDTO(item)
	return internal.SendFormatted(c, 200, dto)
}

// Delete User
// @Summary Delete User
// @Tags User
// @Param id path int true "ID"
// @Success 204
// @Router /users/{id} [delete]
func (r *UserResource) Delete(c *fiber.Ctx) error {
	id := c.Params("id")
	if err := r.CRUD.Delete(c.Context(), id); err != nil {
		return c.Status(500).JSON(fiber.Map{"error": err.Error()})
	}
	return c.SendStatus(204)
}
