// Code generated by gorest. DO NOT EDIT.

package resources

import (
	"github.com/gofiber/fiber/v2"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/nicolasbonnici/gorest/internal/crud"
	"github.com/nicolasbonnici/gorest/internal/api/models"
)

// UsersResource defines REST endpoints for Users model.
// @Summary Users resource
// @Description CRUD operations for Users
// @Tags Users
type UsersResource struct {
	DB   *pgxpool.Pool
	CRUD *crud.CRUD[models.Users]
}

func RegisterUsersRoutes(router fiber.Router, db *pgxpool.Pool) {
	res := &UsersResource{
		DB:   db,
		CRUD: crud.New[models.Users](db),
	}
	router.Get("/users", res.List)
	router.Get("/users/:id", res.Get)
	router.Post("/users", res.Create)
	router.Put("/users/:id", res.Update)
	router.Delete("/users/:id", res.Delete)
}

// List Users
// @Summary List Users
// @Tags Users
// @Produce json
// @Success 200 {array} models.Users
// @Router /users [get]
func (r *UsersResource) List(c *fiber.Ctx) error {
	items, err := r.CRUD.GetAll(c.Context())
	if err != nil {
		return c.Status(500).JSON(fiber.Map{"error": err.Error()})
	}
	if items == nil {
		items = []models.Users{}
	}
	return c.JSON(items)
}

// Get Users by ID
// @Summary Get Users
// @Tags Users
// @Produce json
// @Param id path int true "ID"
// @Success 200 {object} models.Users
// @Router /users/{id} [get]
func (r *UsersResource) Get(c *fiber.Ctx) error {
	id := c.Params("id")
	item, err := r.CRUD.GetByID(c.Context(), id)
	if err != nil {
		return c.Status(404).JSON(fiber.Map{"error": "Not found"})
	}
	return c.JSON(item)
}

// Create Users
// @Summary Create Users
// @Tags Users
// @Accept json
// @Produce json
// @Param input body models.Users true "New Users"
// @Success 201 {object} models.Users
// @Router /users [post]
func (r *UsersResource) Create(c *fiber.Ctx) error {
	var item models.Users
	if err := c.BodyParser(&item); err != nil {
		return c.Status(400).JSON(fiber.Map{"error": "Invalid request body", "details": err.Error()})
	}
	if err := r.CRUD.Create(c.Context(), item); err != nil {
		return c.Status(500).JSON(fiber.Map{"error": err.Error()})
	}
	return c.Status(201).JSON(item)
}

// Update Users
// @Summary Update Users
// @Tags Users
// @Accept json
// @Produce json
// @Param id path int true "ID"
// @Param input body models.Users true "Updated Users"
// @Success 200 {object} models.Users
// @Router /users/{id} [put]
func (r *UsersResource) Update(c *fiber.Ctx) error {
	id := c.Params("id")
	var item models.Users
	if err := c.BodyParser(&item); err != nil {
		return c.Status(400).JSON(fiber.Map{"error": "Invalid request body"})
	}
	if err := r.CRUD.Update(c.Context(), id, item); err != nil {
		return c.Status(500).JSON(fiber.Map{"error": err.Error()})
	}
	return c.JSON(item)
}

// Delete Users
// @Summary Delete Users
// @Tags Users
// @Param id path int true "ID"
// @Success 204
// @Router /users/{id} [delete]
func (r *UsersResource) Delete(c *fiber.Ctx) error {
	id := c.Params("id")
	if err := r.CRUD.Delete(c.Context(), id); err != nil {
		return c.Status(500).JSON(fiber.Map{"error": err.Error()})
	}
	return c.SendStatus(204)
}
