// Code generated by gorest. DO NOT EDIT.

package resources

import (
	"github.com/gofiber/fiber/v2"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/nicolasbonnici/gorest/internal"
	"github.com/nicolasbonnici/gorest/internal/crud"
	"github.com/nicolasbonnici/gorest/internal/api/models"
)

type UserResource struct {
	DB   *pgxpool.Pool
	CRUD *crud.CRUD[models.User]
}

func RegisterUserRoutes(router fiber.Router, db *pgxpool.Pool, jwtSecret string) {
	res := &UserResource{
		DB:   db,
		CRUD: crud.New[models.User](db),
	}
	router.Get("/users", internal.RequireAuth(jwtSecret, res.List))
	router.Get("/users/:id", internal.RequireAuth(jwtSecret, res.Get))
	router.Post("/users", internal.RequireAuth(jwtSecret, res.Create))
	router.Put("/users/:id", internal.RequireAuth(jwtSecret, res.Update))
	router.Delete("/users/:id", internal.RequireAuth(jwtSecret, res.Delete))
}

// List User
// @Summary List User
// @Tags User
// @Produce json,application/ld+json
// @Success 200 {array} models.User
// @Router /users [get]
func (r *UserResource) List(c *fiber.Ctx) error {
	items, err := r.CRUD.GetAll(c.Context())
	if err != nil {
		return c.Status(500).JSON(fiber.Map{"error": err.Error()})
	}
	if items == nil {
		items = []models.User{}
	}
	return internal.SendFormatted(c, 200, items)
}

// Get User by ID
// @Summary Get User
// @Tags User
// @Produce json,application/ld+json
// @Param id path int true "ID"
// @Success 200 {object} models.User
// @Router /users/{id} [get]
func (r *UserResource) Get(c *fiber.Ctx) error {
	id := c.Params("id")
	item, err := r.CRUD.GetByID(c.Context(), id)
	if err != nil {
		return c.Status(404).JSON(fiber.Map{"error": "Not found"})
	}
	return internal.SendFormatted(c, 200, item)
}

// Create User
// @Summary Create User
// @Tags User
// @Accept json
// @Produce json,application/ld+json
// @Param input body models.User true "New User"
// @Success 201 {object} models.User
// @Router /users [post]
func (r *UserResource) Create(c *fiber.Ctx) error {
	var item models.User
	if err := c.BodyParser(&item); err != nil {
		return c.Status(400).JSON(fiber.Map{"error": "Invalid request body", "details": err.Error()})
	}
	if err := r.CRUD.Create(c.Context(), item); err != nil {
		return c.Status(500).JSON(fiber.Map{"error": err.Error()})
	}
	return internal.SendFormatted(c, 201, item)
}

// Update User
// @Summary Update User
// @Tags User
// @Accept json
// @Produce json,application/ld+json
// @Param id path int true "ID"
// @Param input body models.User true "Updated User"
// @Success 200 {object} models.User
// @Router /users/{id} [put]
func (r *UserResource) Update(c *fiber.Ctx) error {
	id := c.Params("id")
	var item models.User
	if err := c.BodyParser(&item); err != nil {
		return c.Status(400).JSON(fiber.Map{"error": "Invalid request body"})
	}
	if err := r.CRUD.Update(c.Context(), id, item); err != nil {
		return c.Status(500).JSON(fiber.Map{"error": err.Error()})
	}
	return internal.SendFormatted(c, 200, item)
}

// Delete User
// @Summary Delete User
// @Tags User
// @Param id path int true "ID"
// @Success 204
// @Router /users/{id} [delete]
func (r *UserResource) Delete(c *fiber.Ctx) error {
	id := c.Params("id")
	if err := r.CRUD.Delete(c.Context(), id); err != nil {
		return c.Status(500).JSON(fiber.Map{"error": err.Error()})
	}
	return c.SendStatus(204)
}
