package internal

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"
)

// generateResourceForStruct generates a resource file for a struct
func generateResourceForStruct(apiDir string, structName string, authCfg *AuthConfig) {
	resourceFile := filepath.Join(apiDir, strings.ToLower(structName)+".go")

	projectRoot, _ := findProjectRoot()
	modelPath := filepath.Join(projectRoot, "internal", "models", strings.ToLower(structName)+".go")
	fields := extractStructFields(modelPath, structName)

	code := generateResourceFromModel(structName, fields, authCfg)
	if err := os.WriteFile(resourceFile, []byte(code), 0644); err != nil {
		log.Fatalf("failed to write resource for %s: %v", structName, err)
	}
	log.Printf("🧩 Generated API resource for model: %s → %s", structName, resourceFile)
}

// generateResourceFromModel generates the resource code from model
func generateResourceFromModel(structName string, fields []StructField, authCfg *AuthConfig) string {
	resourceName := strings.ToLower(structName)
	lowerStructName := strings.ToLower(structName)
	pluralResourceName := pluralize(resourceName)

	requireGetAuth := authCfg != nil && authCfg.RequiresAuth(pluralResourceName, "GET")
	requirePostAuth := authCfg != nil && authCfg.RequiresAuth(pluralResourceName, "POST")
	requirePutAuth := authCfg != nil && authCfg.RequiresAuth(pluralResourceName, "PUT")
	requireDeleteAuth := authCfg != nil && authCfg.RequiresAuth(pluralResourceName, "DELETE")

	wrapHandler := func(handler string, requireAuth bool) string {
		if requireAuth {
			return fmt.Sprintf("helpers.RequireAuth(jwtSecret, res.%s)", handler)
		}
		return fmt.Sprintf("res.%s", handler)
	}

	listRoute := fmt.Sprintf(`router.Get("/%s", %s)`, pluralResourceName, wrapHandler("List", requireGetAuth))
	getRoute := fmt.Sprintf(`router.Get("/%s/:id", %s)`, pluralResourceName, wrapHandler("Get", requireGetAuth))
	postRoute := fmt.Sprintf(`router.Post("/%s", %s)`, pluralResourceName, wrapHandler("Create", requirePostAuth))
	putRoute := fmt.Sprintf(`router.Put("/%s/:id", %s)`, pluralResourceName, wrapHandler("Update", requirePutAuth))
	deleteRoute := fmt.Sprintf(`router.Delete("/%s/:id", %s)`, pluralResourceName, wrapHandler("Delete", requireDeleteAuth))

	needsAuth := requireGetAuth || requirePostAuth || requirePutAuth || requireDeleteAuth
	routesSignature := "router fiber.Router, db database.Database, paginationLimit, paginationMaxLimit int"

	if needsAuth {
		routesSignature = "router fiber.Router, db database.Database, jwtSecret string, paginationLimit, paginationMaxLimit int"
	}

	// Check if model has UserId field
	hasUserIdField := false
	for _, field := range fields {
		if field.Name == "UserId" {
			hasUserIdField = true
			break
		}
	}

	// Generate user_id auto-population code if the field exists
	userIdAutoPopulate := ""
	if hasUserIdField {
		userIdAutoPopulate = `
	// Auto-populate user_id from authenticated user
	if user := helpers.GetAuthenticatedUser(c); user != nil {
		item.UserId = &user.UserID
	}
`
	}

	// Generate conversion functions
	conversionFuncs := generateConversionFunctions(structName, fields)

	return fmt.Sprintf(`// Code generated by gorest. DO NOT EDIT.

package resources

import (
	"github.com/gofiber/fiber/v2"
	"github.com/nicolasbonnici/gorest/internal/crud"
	"github.com/nicolasbonnici/gorest/internal/helpers"
	"github.com/nicolasbonnici/gorest/internal/models"
	"github.com/nicolasbonnici/gorest/internal/api/dtos"
	"github.com/nicolasbonnici/gorest/pkg/database"
)

type %sResource struct {
	DB                 database.Database
	CRUD               *crud.CRUD[models.%s]
	PaginationLimit    int
	PaginationMaxLimit int
}

func Register%sRoutes(%s) {
	res := &%sResource{
		DB:                 db,
		CRUD:               crud.New[models.%s](db),
		PaginationLimit:    paginationLimit,
		PaginationMaxLimit: paginationMaxLimit,
	}
	%s
	%s
	%s
	%s
	%s
}

%s

// List %s
// @Summary List %s
// @Tags %s
// @Produce json,application/ld+json
// @Success 200 {object} helpers.HydraCollection
// @Router /%s [get]
func (r *%sResource) List(c *fiber.Ctx) error {
	limit := helpers.ParseIntQuery(c, "limit", r.PaginationLimit, r.PaginationMaxLimit)
	page := helpers.ParseIntQuery(c, "page", 1, 1000000)
	if page < 1 {
		page = 1
	}
	offset := (page - 1) * limit
	includeCount := c.Query("count", "true") != "false"

	result, err := r.CRUD.GetAllPaginated(helpers.Context(c), crud.PaginationOptions{
		Limit:        limit,
		Offset:       offset,
		IncludeCount: includeCount,
	})
	if err != nil {
		return helpers.SendPaginatedError(c, 500, err.Error())
	}

	dtoItems := make([]dtos.%sDTO, len(result.Items))
	for i, item := range result.Items {
		dtoItems[i] = modelTo%sDTO(item)
	}

	return helpers.SendHydraCollection(c, dtoItems, result.Total, limit, page, r.PaginationLimit)
}

// Get %s by ID
// @Summary Get %s
// @Tags %s
// @Produce json,application/ld+json
// @Param id path int true "ID"
// @Success 200 {object} dtos.%sDTO
// @Router /%s/{id} [get]
func (r *%sResource) Get(c *fiber.Ctx) error {
	id := c.Params("id")
	item, err := r.CRUD.GetByID(helpers.Context(c), id)
	if err != nil {
		return c.Status(404).JSON(fiber.Map{"error": "Not found"})
	}

	dto := modelTo%sDTO(*item)
	return helpers.SendFormatted(c,200, dto)
}

// Create %s
// @Summary Create %s
// @Tags %s
// @Accept json
// @Produce json,application/ld+json
// @Param input body dtos.%sCreateDTO true "New %s"
// @Success 201 {object} dtos.%sDTO
// @Router /%s [post]
func (r *%sResource) Create(c *fiber.Ctx) error {
	var createDTO dtos.%sCreateDTO
	if err := c.BodyParser(&createDTO); err != nil {
		return c.Status(400).JSON(fiber.Map{"error": "Invalid request body", "details": err.Error()})
	}

	item := %sCreateDTOToModel(createDTO)
%s
	ctx := helpers.Context(c)
	if err := r.CRUD.Create(ctx, item); err != nil {
		return c.Status(500).JSON(fiber.Map{"error": err.Error()})
	}

	created, err := r.CRUD.GetByID(ctx, item.Id)
	if err != nil {
		dto := modelTo%sDTO(item)
		return helpers.SendFormatted(c,201, dto)
	}

	dto := modelTo%sDTO(*created)
	return helpers.SendFormatted(c,201, dto)
}

// Update %s
// @Summary Update %s
// @Tags %s
// @Accept json
// @Produce json,application/ld+json
// @Param id path int true "ID"
// @Param input body dtos.%sUpdateDTO true "Updated %s"
// @Success 200 {object} dtos.%sDTO
// @Router /%s/{id} [put]
func (r *%sResource) Update(c *fiber.Ctx) error {
	id := c.Params("id")
	var updateDTO dtos.%sUpdateDTO
	if err := c.BodyParser(&updateDTO); err != nil {
		return c.Status(400).JSON(fiber.Map{"error": "Invalid request body"})
	}

	item := %sUpdateDTOToModel(updateDTO)
%s
	if err := r.CRUD.Update(helpers.Context(c), id, item); err != nil {
		return c.Status(500).JSON(fiber.Map{"error": err.Error()})
	}

	dto := modelTo%sDTO(item)
	return helpers.SendFormatted(c,200, dto)
}

// Delete %s
// @Summary Delete %s
// @Tags %s
// @Param id path int true "ID"
// @Success 204
// @Router /%s/{id} [delete]
func (r *%sResource) Delete(c *fiber.Ctx) error {
	id := c.Params("id")
	if err := r.CRUD.Delete(helpers.Context(c), id); err != nil {
		return c.Status(500).JSON(fiber.Map{"error": err.Error()})
	}
	return c.SendStatus(204)
}
`,
		structName, structName,
		structName, routesSignature, structName, structName,
		listRoute, getRoute, postRoute, putRoute, deleteRoute,
		conversionFuncs,
		structName, structName, structName, pluralResourceName, structName,
		structName, structName,
		structName, structName, structName, structName, pluralResourceName, structName,
		structName,
		structName, structName, structName, structName, structName, structName, pluralResourceName, structName,
		structName,
		lowerStructName,
		userIdAutoPopulate,
		structName, structName,
		structName, structName, structName, structName, structName, structName, pluralResourceName, structName,
		structName,
		lowerStructName,
		userIdAutoPopulate,
		structName,
		structName, structName, structName, pluralResourceName, structName)
}

func generateConversionFunctions(structName string, fields []StructField) string {
	var modelToDTOFields strings.Builder
	for _, field := range fields {
		if field.DTOTag == "-" || field.DTOTag == "write" {
			continue
		}
		modelToDTOFields.WriteString(fmt.Sprintf("\t\t%s: m.%s,\n", field.Name, field.Name))
	}

	var createDTOToModelFields strings.Builder
	for _, field := range fields {
		dbTag := strings.ToLower(field.DBTag)
		if dbTag != FieldID && dbTag != FieldCreatedAt && dbTag != FieldUpdatedAt {
			if field.DTOTag == "-" || field.DTOTag == "read" {
				continue
			}
			createDTOToModelFields.WriteString(fmt.Sprintf("\t\t%s: dto.%s,\n", field.Name, field.Name))
		}
	}

	var updateDTOToModelFields strings.Builder
	for _, field := range fields {
		dbTag := strings.ToLower(field.DBTag)
		if dbTag != FieldID && dbTag != FieldCreatedAt && dbTag != FieldUpdatedAt {
			if field.DTOTag == "-" || field.DTOTag == "read" {
				continue
			}
			updateDTOToModelFields.WriteString(fmt.Sprintf("\t\t%s: dto.%s,\n", field.Name, field.Name))
		}
	}

	lowerStructName := strings.ToLower(structName)
	return fmt.Sprintf(`func modelTo%sDTO(m models.%s) dtos.%sDTO {
	return dtos.%sDTO{
%s	}
}

func %sCreateDTOToModel(dto dtos.%sCreateDTO) models.%s {
	return models.%s{
%s	}
}

func %sUpdateDTOToModel(dto dtos.%sUpdateDTO) models.%s {
	return models.%s{
%s	}
}
`, structName, structName, structName, structName, modelToDTOFields.String(),
		lowerStructName, structName, structName, structName, createDTOToModelFields.String(),
		lowerStructName, structName, structName, structName, updateDTOToModelFields.String())
}
