package internal

import (
	"go/ast"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"strings"
	"fmt"
)

func GenerateAPI(_ interface{}, _ map[string]TableSchema) {
	projectRoot, err := findProjectRoot()
	if err != nil {
		log.Fatalf("failed to find project root: %v", err)
	}

	modelsDir := filepath.Join(projectRoot, "internal", "api", "models")
	apiDir := filepath.Join(projectRoot, "internal", "api", "resources")

	if err := os.MkdirAll(apiDir, 0755); err != nil {
		log.Fatalf("failed to create api/resources dir: %v", err)
	}

	files, err := os.ReadDir(modelsDir)
	if err != nil {
		log.Fatalf("failed to read models dir: %v", err)
	}

	for _, file := range files {
		if !strings.HasSuffix(file.Name(), ".go") {
			continue
		}

		filePath := filepath.Join(modelsDir, file.Name())
		structs := parseStructs(filePath)

		for _, s := range structs {
			generateResourceForStruct(apiDir, s)
		}
	}
}

func parseStructs(path string) []string {
	fs := token.NewFileSet()
	node, err := parser.ParseFile(fs, path, nil, parser.AllErrors)
	if err != nil {
		log.Printf("parse error in %s: %v", path, err)
		return nil
	}

	structs := []string{}
	for _, decl := range node.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok {
			continue
		}
		for _, spec := range gen.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}
			if _, ok := ts.Type.(*ast.StructType); ok {
				structs = append(structs, ts.Name.Name)
			}
		}
	}
	return structs
}

func generateResourceForStruct(apiDir string, structName string) {
	resourceFile := filepath.Join(apiDir, strings.ToLower(structName)+".go")

	code := generateResourceFromModel(structName)
	if err := os.WriteFile(resourceFile, []byte(code), 0644); err != nil {
		log.Fatalf("failed to write resource for %s: %v", structName, err)
	}
	log.Printf("🧩 Generated API resource for model: %s → %s", structName, resourceFile)
}

func generateResourceFromModel(structName string) string {
	resourceName := strings.ToLower(structName)
	// Pluralize the endpoint path
	pluralResourceName := pluralize(resourceName)

	return fmt.Sprintf(`// Code generated by gorest. DO NOT EDIT.

package resources

import (
	"github.com/gofiber/fiber/v2"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/nicolasbonnici/gorest/internal"
	"github.com/nicolasbonnici/gorest/internal/crud"
	"github.com/nicolasbonnici/gorest/internal/api/models"
)

// %sResource defines REST endpoints for %s model.
// @Summary %s resource
// @Description CRUD operations for %s
// @Tags %s
type %sResource struct {
	DB   *pgxpool.Pool
	CRUD *crud.CRUD[models.%s]
}

func Register%sRoutes(router fiber.Router, db *pgxpool.Pool) {
	res := &%sResource{
		DB:   db,
		CRUD: crud.New[models.%s](db),
	}
	router.Get("/%s", res.List)
	router.Get("/%s/:id", res.Get)
	router.Post("/%s", res.Create)
	router.Put("/%s/:id", res.Update)
	router.Delete("/%s/:id", res.Delete)
}

// List %s
// @Summary List %s
// @Tags %s
// @Produce json,application/ld+json
// @Success 200 {array} models.%s
// @Router /%s [get]
func (r *%sResource) List(c *fiber.Ctx) error {
	items, err := r.CRUD.GetAll(c.Context())
	if err != nil {
		return c.Status(500).JSON(fiber.Map{"error": err.Error()})
	}
	if items == nil {
		items = []models.%s{}
	}
	return internal.SendFormatted(c, 200, items)
}

// Get %s by ID
// @Summary Get %s
// @Tags %s
// @Produce json,application/ld+json
// @Param id path int true "ID"
// @Success 200 {object} models.%s
// @Router /%s/{id} [get]
func (r *%sResource) Get(c *fiber.Ctx) error {
	id := c.Params("id")
	item, err := r.CRUD.GetByID(c.Context(), id)
	if err != nil {
		return c.Status(404).JSON(fiber.Map{"error": "Not found"})
	}
	return internal.SendFormatted(c, 200, item)
}

// Create %s
// @Summary Create %s
// @Tags %s
// @Accept json
// @Produce json,application/ld+json
// @Param input body models.%s true "New %s"
// @Success 201 {object} models.%s
// @Router /%s [post]
func (r *%sResource) Create(c *fiber.Ctx) error {
	var item models.%s
	if err := c.BodyParser(&item); err != nil {
		return c.Status(400).JSON(fiber.Map{"error": "Invalid request body", "details": err.Error()})
	}
	if err := r.CRUD.Create(c.Context(), item); err != nil {
		return c.Status(500).JSON(fiber.Map{"error": err.Error()})
	}
	return internal.SendFormatted(c, 201, item)
}

// Update %s
// @Summary Update %s
// @Tags %s
// @Accept json
// @Produce json,application/ld+json
// @Param id path int true "ID"
// @Param input body models.%s true "Updated %s"
// @Success 200 {object} models.%s
// @Router /%s/{id} [put]
func (r *%sResource) Update(c *fiber.Ctx) error {
	id := c.Params("id")
	var item models.%s
	if err := c.BodyParser(&item); err != nil {
		return c.Status(400).JSON(fiber.Map{"error": "Invalid request body"})
	}
	if err := r.CRUD.Update(c.Context(), id, item); err != nil {
		return c.Status(500).JSON(fiber.Map{"error": err.Error()})
	}
	return internal.SendFormatted(c, 200, item)
}

// Delete %s
// @Summary Delete %s
// @Tags %s
// @Param id path int true "ID"
// @Success 204
// @Router /%s/{id} [delete]
func (r *%sResource) Delete(c *fiber.Ctx) error {
	id := c.Params("id")
	if err := r.CRUD.Delete(c.Context(), id); err != nil {
		return c.Status(500).JSON(fiber.Map{"error": err.Error()})
	}
	return c.SendStatus(204)
}
`,
		structName, structName, structName, structName, structName,
		structName, structName,
		structName, structName, structName,
		pluralResourceName, pluralResourceName, pluralResourceName, pluralResourceName, pluralResourceName,
		structName, structName, structName, structName, pluralResourceName, structName, structName,
		structName, structName, structName, structName, pluralResourceName, structName,
		structName, structName, structName, structName, structName, structName, pluralResourceName, structName, structName,
		structName, structName, structName, structName, structName, structName, pluralResourceName, structName, structName,
		structName, structName, structName, pluralResourceName, structName)
}

// pluralize converts a singular word to plural
func pluralize(word string) string {
	// Handle common singular patterns
	if strings.HasSuffix(word, "y") && !isVowel(word[len(word)-2]) {
		// category -> categories, story -> stories
		return word[:len(word)-1] + "ies"
	}
	if strings.HasSuffix(word, "fe") {
		// knife -> knives, wolf -> wolves
		return word[:len(word)-2] + "ves"
	}
	if strings.HasSuffix(word, "f") {
		// shelf -> shelves
		return word[:len(word)-1] + "ves"
	}
	if strings.HasSuffix(word, "s") || strings.HasSuffix(word, "x") ||
		strings.HasSuffix(word, "z") || strings.HasSuffix(word, "ch") ||
		strings.HasSuffix(word, "sh") {
		// class -> classes, box -> boxes, church -> churches, dish -> dishes
		return word + "es"
	}
	// Default: add 's'
	return word + "s"
}

func isVowel(c byte) bool {
	return c == 'a' || c == 'e' || c == 'i' || c == 'o' || c == 'u'
}
