package internal

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"
)

// generateResourceForStruct generates a resource file for a struct
func generateResourceForStruct(apiDir string, structName string, authCfg *AuthConfig) {
	resourceFile := filepath.Join(apiDir, strings.ToLower(structName)+".go")

	projectRoot, _ := findProjectRoot()
	modelPath := filepath.Join(projectRoot, "internal", "api", "models", strings.ToLower(structName)+".go")
	fields := extractStructFields(modelPath, structName)

	code := generateResourceFromModel(structName, fields, authCfg)
	if err := os.WriteFile(resourceFile, []byte(code), 0644); err != nil {
		log.Fatalf("failed to write resource for %s: %v", structName, err)
	}
	log.Printf("🧩 Generated API resource for model: %s → %s", structName, resourceFile)
}

// generateResourceFromModel generates the resource code from model
func generateResourceFromModel(structName string, fields []StructField, authCfg *AuthConfig) string {
	resourceName := strings.ToLower(structName)
	pluralResourceName := pluralize(resourceName)

	requireGetAuth := authCfg != nil && authCfg.RequiresAuth(pluralResourceName, "GET")
	requirePostAuth := authCfg != nil && authCfg.RequiresAuth(pluralResourceName, "POST")
	requirePutAuth := authCfg != nil && authCfg.RequiresAuth(pluralResourceName, "PUT")
	requireDeleteAuth := authCfg != nil && authCfg.RequiresAuth(pluralResourceName, "DELETE")

	wrapHandler := func(handler string, requireAuth bool) string {
		if requireAuth {
			return fmt.Sprintf("internal.RequireAuth(jwtSecret, res.%s)", handler)
		}
		return fmt.Sprintf("res.%s", handler)
	}

	listRoute := fmt.Sprintf(`router.Get("/%s", %s)`, pluralResourceName, wrapHandler("List", requireGetAuth))
	getRoute := fmt.Sprintf(`router.Get("/%s/:id", %s)`, pluralResourceName, wrapHandler("Get", requireGetAuth))
	postRoute := fmt.Sprintf(`router.Post("/%s", %s)`, pluralResourceName, wrapHandler("Create", requirePostAuth))
	putRoute := fmt.Sprintf(`router.Put("/%s/:id", %s)`, pluralResourceName, wrapHandler("Update", requirePutAuth))
	deleteRoute := fmt.Sprintf(`router.Delete("/%s/:id", %s)`, pluralResourceName, wrapHandler("Delete", requireDeleteAuth))

	needsAuth := requireGetAuth || requirePostAuth || requirePutAuth || requireDeleteAuth
	routesSignature := "router fiber.Router, db *pgxpool.Pool"

	if needsAuth {
		routesSignature = "router fiber.Router, db *pgxpool.Pool, jwtSecret string"
	}

	// Generate conversion functions
	conversionFuncs := generateConversionFunctions(structName, fields)

	return fmt.Sprintf(`// Code generated by gorest. DO NOT EDIT.

package resources

import (
	"github.com/gofiber/fiber/v2"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/nicolasbonnici/gorest/internal"
	"github.com/nicolasbonnici/gorest/internal/crud"
	"github.com/nicolasbonnici/gorest/internal/api/models"
	"github.com/nicolasbonnici/gorest/internal/api/dtos"
)

type %sResource struct {
	DB   *pgxpool.Pool
	CRUD *crud.CRUD[models.%s]
}

func Register%sRoutes(%s) {
	res := &%sResource{
		DB:   db,
		CRUD: crud.New[models.%s](db),
	}
	%s
	%s
	%s
	%s
	%s
}

%s

// List %s
// @Summary List %s
// @Tags %s
// @Produce json,application/ld+json
// @Success 200 {array} dtos.%sDTO
// @Router /%s [get]
func (r *%sResource) List(c *fiber.Ctx) error {
	items, err := r.CRUD.GetAll(c.Context())
	if err != nil {
		return c.Status(500).JSON(fiber.Map{"error": err.Error()})
	}

	// Convert models to DTOs
	dtoItems := make([]dtos.%sDTO, len(items))
	for i, item := range items {
		dtoItems[i] = modelTo%sDTO(item)
	}

	return internal.SendFormatted(c, 200, dtoItems)
}

// Get %s by ID
// @Summary Get %s
// @Tags %s
// @Produce json,application/ld+json
// @Param id path int true "ID"
// @Success 200 {object} dtos.%sDTO
// @Router /%s/{id} [get]
func (r *%sResource) Get(c *fiber.Ctx) error {
	id := c.Params("id")
	item, err := r.CRUD.GetByID(c.Context(), id)
	if err != nil {
		return c.Status(404).JSON(fiber.Map{"error": "Not found"})
	}

	// Convert model to DTO
	dto := modelTo%sDTO(*item)
	return internal.SendFormatted(c, 200, dto)
}

// Create %s
// @Summary Create %s
// @Tags %s
// @Accept json
// @Produce json,application/ld+json
// @Param input body dtos.%sCreateDTO true "New %s"
// @Success 201 {object} dtos.%sDTO
// @Router /%s [post]
func (r *%sResource) Create(c *fiber.Ctx) error {
	var createDTO dtos.%sCreateDTO
	if err := c.BodyParser(&createDTO); err != nil {
		return c.Status(400).JSON(fiber.Map{"error": "Invalid request body", "details": err.Error()})
	}

	// Convert DTO to model
	item := createDTOToModel(createDTO)

	if err := r.CRUD.Create(c.Context(), item); err != nil {
		return c.Status(500).JSON(fiber.Map{"error": err.Error()})
	}

	// Convert model to response DTO
	dto := modelTo%sDTO(item)
	return internal.SendFormatted(c, 201, dto)
}

// Update %s
// @Summary Update %s
// @Tags %s
// @Accept json
// @Produce json,application/ld+json
// @Param id path int true "ID"
// @Param input body dtos.%sUpdateDTO true "Updated %s"
// @Success 200 {object} dtos.%sDTO
// @Router /%s/{id} [put]
func (r *%sResource) Update(c *fiber.Ctx) error {
	id := c.Params("id")
	var updateDTO dtos.%sUpdateDTO
	if err := c.BodyParser(&updateDTO); err != nil {
		return c.Status(400).JSON(fiber.Map{"error": "Invalid request body"})
	}

	// Convert DTO to model
	item := updateDTOToModel(updateDTO)

	if err := r.CRUD.Update(c.Context(), id, item); err != nil {
		return c.Status(500).JSON(fiber.Map{"error": err.Error()})
	}

	// Convert model to response DTO
	dto := modelTo%sDTO(item)
	return internal.SendFormatted(c, 200, dto)
}

// Delete %s
// @Summary Delete %s
// @Tags %s
// @Param id path int true "ID"
// @Success 204
// @Router /%s/{id} [delete]
func (r *%sResource) Delete(c *fiber.Ctx) error {
	id := c.Params("id")
	if err := r.CRUD.Delete(c.Context(), id); err != nil {
		return c.Status(500).JSON(fiber.Map{"error": err.Error()})
	}
	return c.SendStatus(204)
}
`,
		structName, structName,
		structName, routesSignature, structName, structName,
		listRoute, getRoute, postRoute, putRoute, deleteRoute,
		conversionFuncs,
		structName, structName, structName, structName, pluralResourceName, structName, structName, structName,
		structName, structName, structName, structName, pluralResourceName, structName, structName,
		structName, structName, structName, structName, structName, structName, pluralResourceName, structName, structName, structName,
		structName, structName, structName, structName, structName, structName, pluralResourceName, structName, structName, structName,
		structName, structName, structName, pluralResourceName, structName)
}

// generateConversionFunctions generates DTO <-> Model conversion functions
func generateConversionFunctions(structName string, fields []StructField) string {
	// Generate modelToDTO
	var modelToDTOFields strings.Builder
	for _, field := range fields {
		if !isSensitiveField(field.Name) {
			modelToDTOFields.WriteString(fmt.Sprintf("\t\t%s: m.%s,\n", field.Name, field.Name))
		}
	}

	// Generate createDTOToModel
	var createDTOToModelFields strings.Builder
	for _, field := range fields {
		dbTag := strings.ToLower(field.DBTag)
		if dbTag != FieldID && dbTag != FieldCreatedAt && dbTag != FieldUpdatedAt {
			createDTOToModelFields.WriteString(fmt.Sprintf("\t\t%s: dto.%s,\n", field.Name, field.Name))
		}
	}

	// Generate updateDTOToModel
	var updateDTOToModelFields strings.Builder
	for _, field := range fields {
		dbTag := strings.ToLower(field.DBTag)
		if dbTag != FieldID && dbTag != FieldCreatedAt && dbTag != FieldUpdatedAt {
			updateDTOToModelFields.WriteString(fmt.Sprintf("\t\t%s: dto.%s,\n", field.Name, field.Name))
		}
	}

	return fmt.Sprintf(`// modelTo%sDTO converts a model to a response DTO
func modelTo%sDTO(m models.%s) dtos.%sDTO {
	return dtos.%sDTO{
%s	}
}

// createDTOToModel converts a CreateDTO to a model
func createDTOToModel(dto dtos.%sCreateDTO) models.%s {
	return models.%s{
%s	}
}

// updateDTOToModel converts an UpdateDTO to a model
func updateDTOToModel(dto dtos.%sUpdateDTO) models.%s {
	return models.%s{
%s	}
}
`, structName, structName, structName, structName, structName, modelToDTOFields.String(),
		structName, structName, structName, createDTOToModelFields.String(),
		structName, structName, structName, updateDTOToModelFields.String())
}
