package internal

import (
	"context"
	"fmt"
	"log"
	"os"
	"strings"

	"github.com/jackc/pgx/v5/pgxpool"
)

type TableSchema struct {
	TableName string
	Columns   []Column
	Relations []Relation
}

type Column struct {
	Name       string
	Type       string
	IsNullable bool
}

type Relation struct {
	ChildTable   string
	ChildColumn  string
	ParentTable  string
	ParentColumn string
}

func LoadSchema(db *pgxpool.Pool) map[string]TableSchema {
	tables := map[string]TableSchema{}

	colQuery := `
	SELECT table_name, column_name, is_nullable, data_type
	FROM information_schema.columns
	WHERE table_schema='public'
	ORDER BY table_name, ordinal_position;
	`

	rows, err := db.Query(context.Background(), colQuery)
	if err != nil {
		log.Fatal(err)
	}
	defer rows.Close()

	for rows.Next() {
		var table, col, nullable, dataType string
		if err := rows.Scan(&table, &col, &nullable, &dataType); err != nil {
			log.Fatal(err)
		}
		if _, ok := tables[table]; !ok {
			tables[table] = TableSchema{TableName: table, Columns: []Column{}, Relations: []Relation{}}
		}
		ts := tables[table]
		ts.Columns = append(ts.Columns, Column{
			Name:       col,
			Type:       dataType,
			IsNullable: nullable == "YES",
		})
		tables[table] = ts
	}

	relQuery := `
	SELECT
		kcu.table_name AS child_table,
		kcu.column_name AS child_column,
		ccu.table_name AS parent_table,
		ccu.column_name AS parent_column
	FROM
		information_schema.key_column_usage kcu
	JOIN information_schema.constraint_column_usage ccu
		ON kcu.constraint_name = ccu.constraint_name
	WHERE kcu.table_schema='public';
	`
	relRows, err := db.Query(context.Background(), relQuery)
	if err != nil {
		log.Fatal(err)
	}
	defer relRows.Close()

	for relRows.Next() {
		var r Relation
		if err := relRows.Scan(&r.ChildTable, &r.ChildColumn, &r.ParentTable, &r.ParentColumn); err != nil {
			log.Fatal(err)
		}
		ts := tables[r.ChildTable]
		ts.Relations = append(ts.Relations, r)
		tables[r.ChildTable] = ts
	}

	return tables
}

func GenerateCRUD() {
	os.MkdirAll("gen/crud", 0755)

	crudCode := `// Code generated by gorest. DO NOT EDIT.

package crud

import (
	"context"
	"fmt"
	"reflect"
	"strings"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/nicolasbonnici/gorest/gen/models"
)

type CRUD[T models.Model] struct {
	DB *pgxpool.Pool
}

func New[T models.Model](db *pgxpool.Pool) *CRUD[T] {
	return &CRUD[T]{DB: db}
}

func (c *CRUD[T]) Create(ctx context.Context, m T) error {
	v := reflect.ValueOf(m)
	t := reflect.TypeOf(m)

	var cols []string
	var vals []interface{}
	var placeholders []string

	for i := 0; i < t.NumField(); i++ {
		field := t.Field(i)
		tag := field.Tag.Get("db")
		if tag == "" || tag == "id" || tag == "created_at" || tag == "updated_at" {
			continue
		}
		cols = append(cols, tag)
		vals = append(vals, v.Field(i).Interface())
		placeholders = append(placeholders, fmt.Sprintf("$%d", len(vals)))
	}

	query := fmt.Sprintf(
		"INSERT INTO %s (%s) VALUES (%s)",
		m.TableName(),
		strings.Join(cols, ", "),
		strings.Join(placeholders, ", "),
	)
	_, err := c.DB.Exec(ctx, query, vals...)
	return err
}

func (c *CRUD[T]) GetAll(ctx context.Context) ([]T, error) {
	var zero T
	t := reflect.TypeOf(zero)

	var cols []string
	for i := 0; i < t.NumField(); i++ {
		field := t.Field(i)
		tag := field.Tag.Get("db")
		if tag != "" {
			cols = append(cols, tag)
		}
	}

	query := fmt.Sprintf("SELECT %s FROM %s", strings.Join(cols, ", "), zero.TableName())

	rows, err := c.DB.Query(ctx, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []T
	for rows.Next() {
		var item T
		v := reflect.ValueOf(&item).Elem()

		fields := make([]interface{}, t.NumField())
		for i := 0; i < t.NumField(); i++ {
			fields[i] = v.Field(i).Addr().Interface()
		}

		if err := rows.Scan(fields...); err != nil {
			return nil, err
		}
		results = append(results, item)
	}
	return results, rows.Err()
}

func (c *CRUD[T]) GetByID(ctx context.Context, id any) (*T, error) {
	var item T
	t := reflect.TypeOf(item)

	var cols []string
	for i := 0; i < t.NumField(); i++ {
		field := t.Field(i)
		tag := field.Tag.Get("db")
		if tag != "" {
			cols = append(cols, tag)
		}
	}

	query := fmt.Sprintf("SELECT %s FROM %s WHERE id = $1", strings.Join(cols, ", "), item.TableName())

	row := c.DB.QueryRow(ctx, query, id)

	v := reflect.ValueOf(&item).Elem()

	fields := make([]interface{}, t.NumField())
	for i := 0; i < t.NumField(); i++ {
		fields[i] = v.Field(i).Addr().Interface()
	}

	if err := row.Scan(fields...); err != nil {
		return nil, err
	}
	return &item, nil
}

func (c *CRUD[T]) Update(ctx context.Context, id any, m T) error {
	v := reflect.ValueOf(m)
	t := reflect.TypeOf(m)

	var setClauses []string
	var vals []interface{}
	paramIdx := 1

	for i := 0; i < t.NumField(); i++ {
		field := t.Field(i)
		tag := field.Tag.Get("db")
		if tag == "" || tag == "id" || tag == "created_at" {
			continue
		}
		setClauses = append(setClauses, fmt.Sprintf("%s = $%d", tag, paramIdx))
		vals = append(vals, v.Field(i).Interface())
		paramIdx++
	}

	vals = append(vals, id)
	query := fmt.Sprintf(
		"UPDATE %s SET %s WHERE id = $%d",
		m.TableName(),
		strings.Join(setClauses, ", "),
		paramIdx,
	)

	_, err := c.DB.Exec(ctx, query, vals...)
	return err
}

func (c *CRUD[T]) Delete(ctx context.Context, id any) error {
	var zero T
	query := fmt.Sprintf("DELETE FROM %s WHERE id = $1", zero.TableName())
	_, err := c.DB.Exec(ctx, query, id)
	return err
}

type Repository[T any] interface {
	Create(ctx context.Context, m T) error
	GetAll(ctx context.Context) ([]T, error)
	GetByID(ctx context.Context, id any) (*T, error)
	Update(ctx context.Context, id any, m T) error
	Delete(ctx context.Context, id any) error
}
`

	filePath := "gen/crud/crud.go"
	if err := os.WriteFile(filePath, []byte(crudCode), 0644); err != nil {
		log.Fatalf("failed to write CRUD code: %v", err)
	}
	fmt.Printf("✅ Generated CRUD package → %s\n", filePath)
}

func GenerateStructs(tables map[string]TableSchema) {
	os.MkdirAll("gen/models", 0755)

	// Generate Model interface
	modelInterfaceCode := `// Code generated by gorest. DO NOT EDIT.

package models

// Model is the interface that all generated models must implement
type Model interface {
	TableName() string
}
`
	modelInterfacePath := "gen/models/model.go"
	if err := os.WriteFile(modelInterfacePath, []byte(modelInterfaceCode), 0644); err != nil {
		log.Fatalf("failed to write Model interface: %v", err)
	}
	fmt.Printf("✅ Generated Model interface → %s\n", modelInterfacePath)

	for _, table := range tables {
		structName := toCamelCase(table.TableName)
        switch structName {
        case "model":
            continue
        }

		filePath := fmt.Sprintf("gen/models/%s.go", strings.ToLower(structName))

		// Check if any field uses time.Time
		needsTime := false
		for _, col := range table.Columns {
			if strings.Contains(col.Type, "timestamp") {
				needsTime = true
				break
			}
		}

		var b strings.Builder
		b.WriteString("package models\n\n")
		if needsTime {
			b.WriteString("import \"time\"\n\n")
		}
		b.WriteString("type " + structName + " struct {\n")

		for _, col := range table.Columns {
			fieldName := toCamelCase(col.Name)
			fieldType := pgToGoType(col.Type, col.IsNullable)

			// Add omitempty for id, timestamps, and nullable fields
			omitempty := ""
			if col.Name == "id" || col.Name == "created_at" || col.Name == "updated_at" || col.IsNullable {
				omitempty = ",omitempty"
			}

			jsonTag := fmt.Sprintf("`json:\"%s%s\" db:\"%s\"`", col.Name, omitempty, col.Name)
			b.WriteString(fmt.Sprintf("\t%s %s %s\n", fieldName, fieldType, jsonTag))
		}
		b.WriteString("}\n")
		b.WriteString("\n")
		b.WriteString("func (" + structName + ") TableName() string {\n")
		b.WriteString("	return \"" + table.TableName + "\" \n")
		b.WriteString("}\n")

		os.WriteFile(filePath, []byte(b.String()), 0644)
		fmt.Printf("✅ Generated struct for table: %s → %s\n", table.TableName, filePath)
	}
}

func GenerateOpenAPI(tables map[string]TableSchema) {
	os.MkdirAll("gen/api", 0755)
	filePath := "gen/api/openapi_gen.go"

	var b strings.Builder
	b.WriteString("package api\n\n")
	b.WriteString("// Auto-generated OpenAPI schema stubs\n\n")

	for _, table := range tables {
		resource := toCamelCase(table.TableName)
		b.WriteString(fmt.Sprintf("// %sResource defines OpenAPI schema and endpoints for %s\n", resource, table.TableName))
		b.WriteString(fmt.Sprintf("type %sResource struct {}\n\n", resource))
	}

	os.WriteFile(filePath, []byte(b.String()), 0644)
	fmt.Println("✅ Generated OpenAPI resource stubs → gen/api/openapi_gen.go")
}

func pgToGoType(pgType string, nullable bool) string {
	base := map[string]string{
		"integer":  "int",
		"bigint":   "int64",
		"smallint": "int16",
		"text":     "string",
		"varchar":  "string",
		"character varying": "string",
		"boolean":  "bool",
		"timestamp without time zone": "time.Time",
		"timestamp with time zone": "time.Time",
		"timestamp": "time.Time",
		"uuid": "string",
		"numeric": "float64",
		"double precision": "float64",
		"real": "float32",
		"json": "map[string]interface{}",
		"jsonb": "map[string]interface{}",
	}
	goType, ok := base[pgType]
	if !ok {
		goType = "interface{}"
	}

	// Make timestamps always nullable for omitempty to work properly
	isTimestamp := goType == "time.Time"
	if (nullable || isTimestamp) && goType != "interface{}" {
		goType = "*" + goType
	}
	return goType
}

func toCamelCase(s string) string {
	parts := strings.Split(s, "_")
	for i, p := range parts {
		parts[i] = strings.Title(p)
	}
	return strings.Join(parts, "")
}

func ScaffoldAll(db *pgxpool.Pool) {
	tables := LoadSchema(db)
	GenerateStructs(tables)
	GenerateOpenAPI(tables)
}
